<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en-US">
<!--<![endif]-->

<%@ taglib prefix="s" uri="/struts-tags"%>

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Xseed</title>
	<meta name="description" content="A free html template with Sketch design made with Bootstrap">
	<meta name="keywords" content="free html template, bootstrap, ui kit, sass" />
	<meta name="author" content="Codrops" />
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- favicon generated by http://realfavicongenerator.net/ -->
	<link rel="apple-touch-icon" sizes="57x57" href="<%=request.getContextPath() %>/pages/img/favicon/apple-touch-icon-57x57.png">
	<link rel="apple-touch-icon" sizes="60x60" href="<%=request.getContextPath() %>/pages/img/favicon/apple-touch-icon-60x60.png">
	<link rel="apple-touch-icon" sizes="72x72" href="<%=request.getContextPath() %>/pages/img/favicon/apple-touch-icon-72x72.png">
	<link rel="apple-touch-icon" sizes="76x76" href="<%=request.getContextPath() %>/pages/img/favicon/apple-touch-icon-76x76.png">
	<link rel="apple-touch-icon" sizes="114x114" href="<%=request.getContextPath() %>/pages/img/favicon/apple-touch-icon-114x114.png">
	<link rel="apple-touch-icon" sizes="120x120" href="<%=request.getContextPath() %>/pages/img/favicon/apple-touch-icon-120x120.png">
	<link rel="apple-touch-icon" sizes="144x144" href="<%=request.getContextPath() %>/pages/img/favicon/apple-touch-icon-144x144.png">
	<link rel="apple-touch-icon" sizes="152x152" href="<%=request.getContextPath() %>/pages/img/favicon/apple-touch-icon-152x152.png">
	<link rel="apple-touch-icon" sizes="180x180" href="<%=request.getContextPath() %>/pages/img/favicon/apple-touch-icon-180x180.png">
	<link rel="icon" type="image/png" href="<%=request.getContextPath() %>/pages/img/favicon/favicon-32x32.png" sizes="32x32">
	<link rel="icon" type="image/png" href="<%=request.getContextPath() %>/pages/img/favicon/favicon-194x194.png" sizes="194x194">
	<link rel="icon" type="image/png" href="<%=request.getContextPath() %>/pages/img/favicon/favicon-96x96.png" sizes="96x96">
	<link rel="icon" type="image/png" href="<%=request.getContextPath() %>/pages/img/favicon/android-chrome-192x192.png" sizes="192x192">
	<link rel="icon" type="image/png" href="<%=request.getContextPath() %>/pages/img/favicon/favicon-16x16.png" sizes="16x16">
	<link rel="manifest" href="<%=request.getContextPath() %>/pages/img/favicon/manifest.json">
	<link rel="mask-icon" href="<%=request.getContextPath() %>/pages/img/favicon/safari-pinned-tab.svg" color="#5bbad5">
	<link rel="shortcut icon" href="<%=request.getContextPath() %>/pages/img/favicon/favicon.ico">
	<meta name="msapplication-TileColor" content="#66e0e5">
	<meta name="msapplication-TileImage" content="<%=request.getContextPath() %>/pages/img/favicon/mstile-144x144.png">
	<meta name="msapplication-config" content="<%=request.getContextPath() %>/pages/img/favicon/browserconfig.xml">
	<meta name="theme-color" content="#ffffff">
	<!-- end favicon links -->
	<link rel="stylesheet" href="<%=request.getContextPath() %>/pages/css/bootstrap.min.css" />
	<link rel="stylesheet" href="<%=request.getContextPath() %>/pages/css/normalize.min.css">
	<link rel="stylesheet" href="<%=request.getContextPath() %>/pages/css/animate.min.css">
	<link rel="stylesheet" href="<%=request.getContextPath() %>/pages/css/flickity.min.css">
	<link rel="stylesheet" href="<%=request.getContextPath() %>/pages/css/styles.css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="<%=request.getContextPath()%>/pages/css/style.css" type="text/css" />
	<!-- Include one of jTable styles. -->
	<link href="<%=request.getContextPath()%>/pages/js/jtable.2.4.0/themes/metro/blue/jtable.min.css" rel="stylesheet" type="text/css" />
 
 	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.0/jquery-ui.min.js"></script>
	<!-- Include jTable script file. -->
	<script src="<%=request.getContextPath()%>/pages/js/jtable.2.4.0/jquery.jtable.min.js" type="text/javascript"></script>
	
	<script type="text/javascript">
	function enableStep1(){
		//document.getElementById("step1").style.display = 'block';
		//document.getElementById("step2").style.display = 'none';
		//document.getElementById("step3").style.display = 'none';
		document.getElementById("logindiv").style.display = 'block';
		document.getElementById("signupdiv").style.display = 'none';
		//document.getElementById("steprow1").style.display = 'block';
		//document.getElementById("steprow2").style.display = 'block';
		//document.getElementById("steprow3").style.display = 'block';
		//document.getElementById("steprow4").style.display = 'none';
	}
	
	</script>
	
</head>

<body onload="javascript:enableStep1()">
	<!--[if lt IE 8]>
	<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
	<![endif]-->
	<div class="container-fluid">
		<div class="row">
			<div class="header-nav-wrapper">
				<div class="logo">
					<a href="<%=request.getContextPath() %>/pages/index.jsp"><img src="<%=request.getContextPath() %>/pages/img/xseed.png" alt="Xseed"></a>
				</div>
				<div class="primary-nav-wrapper">
					<nav>
						<ul class="primary-nav">
							<li><a href="#intro">The collective</a></li>
							<li><a href="<%=request.getContextPath() %>/pages/getStarted.jsp">Get Started</a></li>
						</ul>
					</nav>
					<div class="secondary-nav-wrapper">
						<ul class="secondary-nav">
							<li class="subscribe"><a href="<%=request.getContextPath() %>/pages/signup.jsp">Login</a></li>
							<!-- <li class="search"><a href="#search" class="show-search"><i class="fa fa-search"></i></a></li> -->
						</ul>
					</div>
					<!-- <div class="search-wrapper">
						<ul class="search">
							<li>
								<input type="text" id="search-input" placeholder="Start typing then hit enter to search">
							</li>
							<li>
								<a href="#" class="hide-search"><i class="fa fa-close"></i></a>
							</li>
						</ul>
					</div> -->
				</div>
				<div class="navicon">
					<a class="nav-toggle" href="#"><span></span></a>
				</div>
			</div>
		</div>
	</div>
	
	<footer class="has-padding footer-bg" style="padding: 1% 0;">
	
		
	</footer>
	
 	<!-- END SECTION: Freebies -->
	<!-- SECTION: Get started -->
			<div class="row">
			<br>
				<div class="col-md-12">
				<br>
				<h4>Login/SignUp</h4>
				</div>
			</div>
	
	<section class="get-started has-padding text-center" id="login" style="padding: 3% 0;">
	<div class="container">
			<div class="row">
			<div class="col-md-12 wp4" style="width:70%; padding-left: 30%;">
	<div id="logindiv" style="display: none">
				
    <form class="form-signin">   
    <br>    
      <input type="text" id="user" class="form-control" name="username" placeholder="Email Address" required="" autofocus="" />
      <br>
      <input type="password" id="pwd" class="form-control" name="password" placeholder="Password" required=""/>  
      <br>    
      <label class="checkbox">
        <input type="checkbox" value="remember-me" id="rememberMe" name="rememberMe"> Remember me
      </label>
      <br>
      <a class="btn btn-lg btn-primary btn-block" onclick="logincheck();">Login</a>
      <br>
      
      
          
    </form>	
    <br>
    <a onclick="signup()">SignUp!</a> 
    
    </div>
	
	<div id="signupdiv" style="display:none">
	
	<form class="form-signin">       
      First Name<input type="text" class="form-control" name="firstname" required="" autofocus=""></input>
      <br>
      Last Name<input type="text" class="form-control" name="lastname"  required="" autofocus=""></input>
      <br>
      Address<input type="text" class="form-control" name="address" required="" autofocus=""></input>
      <br>
      Password<input type="password" class="form-control" name="password" placeholder="Password" required=""></input>      
     <br>
      <button class="btn btn-lg btn-primary btn-block" type="submit" onclick="login()">Sign Up</button>   
    </form>		</div>
			</div>
		</div>
	</div>
	
	</section>
	<!-- END SECTION: Get started -->
	<!-- SECTION: Footer -->
	<footer class="has-padding footer-bg" style="padding: 1% 0;">
	
		<!-- <div class="container">
			<div class="row">
				<div class="col-md-4 footer-branding">
					//<img class="footer-branding-logo" src="img/xseed.png" alt="xseed">
					<p>A free website template</p>
				</div>
			</div> -->
			<!-- <div class="row">
				<div class="col-md-12 footer-nav">
					<ul class="footer-primary-nav">
						<li><a href="#intro">The Collective</a></li>
						<li><a href="#team">The Crew</a></li>
						<li><a href="#articles">Articles</a></li>
						<li><a href="#freebies">Freebies</a></li>
						<li><a href="#get-started">Subscribe</a></li>
					</ul>
					<ul class="footer-share">
						<li><a href="http://tympanus.net/codrops/licensing/">Licence</a></li>
						<li><a href="#" class="share-trigger"><i class="fa fa-share"></i>Share</a></li>
					</ul>
					<div class="share-dropdown">
						<ul>
							<li><a href="#" class="share-twitter"><i class="fa fa-twitter"></i></a></li>
							<li><a href="#" class="share-facebook"><i class="fa fa-facebook"></i></a></li>
							<li><a href="#" class="share-linkedin"><i class="fa fa-linkedin"></i></a></li>
						</ul>
					</div>
					<ul class="footer-secondary-nav">
						<li><p>A free website template</p></li>
					</ul>
				</div>
			</div>
		</div> -->
	</footer>
	<!-- END SECTION: Footer -->
	<!-- JS CDNs -->
	<script type="text/javascript" src="http://vjs.zencdn.net/5.4.6/video.min.js"></script>
	<!-- jQuery local fallback -->
	<script>
	window.jQuery || document.write('<script type="text/javascript" src="<%=request.getContextPath() %>/pages/js/min/jquery-1.11.2.min.js"><\/script>')
	</script>
	<!-- JS Locals -->
	<script type="text/javascript" src="<%=request.getContextPath() %>/pages/js/min/bootstrap.min.js"></script>
	<script type="text/javascript" src="<%=request.getContextPath() %>/pages/js/min/modernizr-2.8.3-respond-1.4.2.min.js"></script>
	<script type="text/javascript" src="<%=request.getContextPath() %>/pages/js/min/retina.min.js"></script>
	<script type="text/javascript" src="<%=request.getContextPath() %>/pages/js/min/jquery.waypoints.min.js"></script>
	<script type="text/javascript" src="<%=request.getContextPath() %>/pages/js/min/flickity.pkgd.min.js"></script>
	<script type="text/javascript" src="<%=request.getContextPath() %>/pages/js/min/scripts-min.js"></script>
	<!-- Google Analytics: change UA-XXXXX-X to be your site's ID and uncomment -->
	<!--
	<script>
	(function(b, o, i, l, e, r) {
		b.GoogleAnalyticsObject = l;
		b[l] || (b[l] =
			function() {
				(b[l].q = b[l].q || []).push(arguments)
			});
		b[l].l = +new Date;
		e = o.createElement(i);
		r = o.getElementsByTagName(i)[0];
		e.src = '//www.google-analytics.com/analytics.js';
		r.parentNode.insertBefore(e, r)
	}(window, document, 'script', 'ga'));
	ga('create', 'UA-XXXXX-X', 'auto');
	ga('send', 'pageview');
	</script>
	-->
	<script type="text/javascript">
	function checkFile(){
		var check = document.getElementById("fileUpload").value;
		if(check==""){
			alert("Please browse template File.");
			return false;
		}
		else{
			return true;
		}
				
	}
	
	function login(){
		document.getElementById("signupdiv").style.display= 'none';
		document.getElementById("logindiv").style.display= 'block';
	}
	
	function signup(){
		document.getElementById("signupdiv").style.display= 'block';
		document.getElementById("logindiv").style.display= 'none';
	}
	
	function logincheck(){
		var usr = document.getElementById("user").value;
		var p = document.getElementById("pwd").value;

		// on click Sign In Button checks that username =='admin' and password == 'admin'
                  if(usr=='admin' && p=='admin') {
                // alert("Login Successfull"); 
                 window.location.href = "<%=request.getContextPath() %>/getStartedPage";
           }
             else {
            	 
            	 
          		
          		window.location.href = "<%=request.getContextPath() %>/pages/clienthome.jsp";
             }

                  
	}
	
	
	
	</script>
</body>

</html>
